root: true
parser: '@typescript-eslint/parser'
parserOptions:
  tsconfigRootDir: .
  project: [./tsconfig.json]
plugins:
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
rules:
  no-duplicate-imports: error
  no-template-curly-in-string: error
  eqeqeq: error
